
error_two_same_strong_funcs:
	gcc foo1.c bar1.c

error_two_same_strong_vars:
	gcc foo2.c bar2.c

no_error_two_strong_weak_vars:
	gcc foo3.c bar3.c

no_error_two_weak_vars:
	gcc foo4.c bar4.c

warning_two_different_types_weak_vars:
	gcc foo5.c bar5.c

